// Generated by npm run build:info. Do not edit by hand.
(() => {
  "use strict";
  const ns = globalThis.DominionLens ||= {};
  ns.buildInfo = Object.freeze({"version":"0.1.2","build":"5fea6dd1b8e9"});
})();
