import { createHash } from 'node:crypto';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';

const root = path.resolve(import.meta.dirname, '..');
const metadataFile = 'lib/build-info.js';

export async function calculateBuildInfo(projectRoot = root) {
  const dir = path.join(projectRoot, 'extension');
  const manifest = JSON.parse(await readFile(path.join(dir, 'manifest.json'), 'utf8'));
  // Generated labels do not participate in their own digest.
  delete manifest.version_name;
  const files = [];
  async function walk(relative = '') {
    for (const entry of await readdir(path.join(dir, relative), { withFileTypes: true })) {
      const name = path.posix.join(relative, entry.name);
      if (entry.name === '.DS_Store') continue;
      if (entry.isDirectory()) await walk(name);
      else if (entry.isFile() && name !== metadataFile) files.push(name);
    }
  }
  await walk();
  const hash = createHash('sha256');
  for (const file of files.sort()) {
    const source = file === 'manifest.json' ? Buffer.from(JSON.stringify(manifest)) : await readFile(path.join(dir, file));
    hash.update(`${file}\0${source.length}\0`).update(source);
  }
  const info = { version: manifest.version, build: hash.digest('hex').slice(0, 12) };
  return {
    ...info,
    versionName: `${info.version} (${info.build})`,
    source: `// Generated by npm run build:info. Do not edit by hand.\n(() => {\n  "use strict";\n  const ns = globalThis.DominionLens ||= {};\n  ns.buildInfo = Object.freeze(${JSON.stringify(info)});\n})();\n`
  };
}

export async function checkBuildInfo(projectRoot = root) {
  const info = await calculateBuildInfo(projectRoot);
  const dir = path.join(projectRoot, 'extension');
  const manifest = JSON.parse(await readFile(path.join(dir, 'manifest.json'), 'utf8'));
  const pkg = JSON.parse(await readFile(path.join(projectRoot, 'package.json'), 'utf8'));
  assert.equal(pkg.version, info.version, 'package.json and Manifest versions must match');
  const message = 'Build information is stale. Run npm run build:info and commit the generated files.';
  assert.equal(manifest.version_name, info.versionName, message);
  assert.equal(await readFile(path.join(dir, metadataFile), 'utf8'), info.source, message);
  return info;
}

export async function writeBuildInfo(projectRoot = root) {
  const info = await calculateBuildInfo(projectRoot);
  const file = path.join(projectRoot, 'extension', 'manifest.json');
  const manifest = JSON.parse(await readFile(file, 'utf8'));
  manifest.version_name = info.versionName;
  await writeFile(file, JSON.stringify(manifest, null, 2) + '\n');
  await writeFile(path.join(projectRoot, 'extension', metadataFile), info.source);
  return info;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  assert.deepEqual(process.argv.slice(2), ['--write'], 'Use npm run build:info to regenerate build information');
  console.log((await writeBuildInfo()).versionName);
}
